### ISSUE TITLE
music doesnt work

### ISSUE THREAD

**Issue by Qnauv** [RHeavenStudio/HeavenStudio#182]
When I put music it doesn't work. I don't hear the music. I tried using a mp3 wav and ogg but none of them work. I'm on Windows 10.

**Comment by blank3times** [comment]
May relate to #119

**Comment by Saraistupid** [comment]
Hello! That seems to be a common issue, can you get a log file?
If you don't know how to here's a step by step guide:
> Getting the log of Heaven Studio:
> - Close Heaven Studio (to get a fresh log file)
> - Re-Open Heaven Studio
> - Play until you experience your bug
> - Close Heaven Studio
> - If you are on Windows go to `%USERPROFILE%\AppData\LocalLow\Megaminerzero\Heaven Studio\`
> - If you are on Linux go to `~/.config/unity3d/Megaminerzero/Heaven Studio/`
> - If you are on MacOS go to `~/Library/Logs/Megaminerzero/Heaven Studio`
> - Send the Player.log file from that directory here

**Comment by AstrlJelly** [comment]
Hey; I don't know if this belongs here, but I've had that issue before. Importing the song into Audacity and changing the project rate to something else completely fixed the problem for me. Also, when normally importing a song, the program hitches, but when I was having the issue, it was as if it didn't even recognize that I did anything. Hope this helps!
