### ISSUE TITLE
Some assets don't work in macOS and Linux Actions builds

### ISSUE THREAD

**Issue by LeWolfYT** [RHeavenStudio/HeavenStudio#243]
it's pink

**Comment by Saraistupid** [comment]
Github user read the README.md challenge (impossible)

![image](https://user-images.githubusercontent.com/37207067/214963880-05dbedfc-54a2-49f8-9685-908d971f4544.png)

**Comment by LeWolfYT** [comment]
Got it!

**Comment by minenice55** [comment]
leads me to think that this issue is caused by missing dependancy links when building assetbundles via autobuild, will hopefully remedy in upcoming PR

**Comment by minenice55** [comment]
closed by #486
