### ISSUE TITLE
crop stomp screen moving problem

### ISSUE THREAD

**Issue by dirt-bee** [RHeavenStudio/HeavenStudio#247]
when putting alot of moles in a row, the screen starts to move down, making black part show, this seems to be difficult to patch but im not sure
![Screenshot_1](https://user-images.githubusercontent.com/115891182/215552923-e1fab106-a0aa-44bd-8e9c-8a06090598c5.png)
![Screenshot_3](https://user-images.githubusercontent.com/115891182/215552962-a8492689-1a8e-427e-8825-02ef155a1e41.png)

**Comment by ThatZeoMan** [comment]
looks like the screen shake is not resetting. Should actually be pretty easy to fix

**Comment by patataofcourse** [comment]
(sorry had to)

**Comment by dirt-bee** [comment]
> (sorry had to)

its perfectly fine, im portuguese so my english can be a bit weird at times.
