### ISSUE TITLE
Ringside "pose for the fans" newspaper sometimes uses the wrong body parts

### ISSUE THREAD

**Issue by red031000** [RHeavenStudio/HeavenStudio#266]
This is a somewhat odd issue, as it only occurs sometimes, under conditions I'm not sure of, I've only had it occur after the first newspaper, however it causes some rather odd looking poses, usually it's only the hands, however, I've attached one of the more extreme cases
![image](https://user-images.githubusercontent.com/13968885/217713516-7c33223f-7d76-456f-bbe9-9c2f93396e6b.png)

**Comment by minenice55** [comment]
@Rapandrasmus or @evdial was this fixed?

**Comment by Rapandrasmus** [comment]
@minenice55 it was not fixed, it might have to do with objects being disabled/enabled in the animation and unity sometimes not being able ro do that. The solution I'm thinking about is just making everything transparent/opaque instead of disabling/enabling them.

**Comment by Rapandrasmus** [comment]
this should also be closed because I also fixed this
