### ISSUE TITLE
DJ Yellow Banter Prefunction will play the first quote on switch-in

### ISSUE THREAD

**Issue by blank3times** [RHeavenStudio/HeavenStudio#271]
If I were to be on any other game, and put a line (such as "Oh yeah"), then afterwards switch to DJ school, it will play the "Check it out" very quickly when you switch in (Despite not actually putting one down).

**Comment by patataofcourse** [comment]
can you show footage of this happening?

**Comment by blank3times** [comment]
I don't have an easy way to record my screen that I know of, but here is a .riq that creates this bug for me (if that helps recreate it):

[HS Bug Recreation 271 RIQ.zip](https://github.com/RHeavenStudio/HeavenStudio/files/10738417/HS.Bug.Recreation.271.RIQ.zip)

**Comment by blank3times** [comment]
https://user-images.githubusercontent.com/105398129/218906330-fe1a103c-bfa9-4310-81b0-f0eb2f987585.mp4

**Comment by patataofcourse** [comment]
thank you! i'll keep you updated

**Comment by blank3times** [comment]
Great! Somehow when it switches games or starts to play, it knows it should have done it but thinks it hasn't and just does it all at once. That's not limited to this, but it's the only one I can think of that actually happens if you go from start to finish.

**Comment by blank3times** [comment]
Thanks y'all for paying attention to semi-obscure bugs
