### ISSUE TITLE
Autoplay can miss 

### ISSUE THREAD

**Issue by loveyhub** [RHeavenStudio/HeavenStudio#274]
if the input is when the remix starts then autoplay can actually miss. 
![Screenshot](https://user-images.githubusercontent.com/125224060/218896374-bc2be4b4-c690-4bc1-b19d-704164568b46.png)

**Comment by loveyhub** [comment]
also someone tell me how to add labels

**Comment by Saraistupid** [comment]
like this :)
anyways, this is known and we'll work on a fix

**Comment by dirt-bee** [comment]
its quite normal for it to mess up when the game lags, but its very unusual for it to happen while no lag happens...
