### ISSUE TITLE
the upbeat glitch

### ISSUE THREAD

**Issue by loveyhub** [RHeavenStudio/HeavenStudio#283]
basically, in mr.upbeat if you put multiple start stepping blocks next to each other mr.upbeat will skip stepping the opposite direction and just stay where he was.

**Comment by patataofcourse** [comment]
can you show footage or an example of this happening?

**Comment by loveyhub** [comment]
https://youtu.be/LXfvPFm76ss

**Comment by AstrlJelly** [comment]
uhh this was technically fixed in #418 ig so it can be closed
