### ISSUE TITLE
Version field on RIQ files

### ISSUE THREAD

**Issue by patataofcourse** [RHeavenStudio/HeavenStudio#295]
For the first stable release of HS, .riq files should include a version field (`"version_major": 1, "version_minor": 0`), so that:

- breaking changes, those that make an old RIQ incompatible with the newer version, increase the major version by 1 (and reset minor version to 0), and the program needs to know how to adapt the RIQ
- non-breaking changes, those that dont make old RIQs incompatible with the newer version but do make newer RIQs incompatible with an older stable release of HS, increase the minor version by 1
- version is only increased on a breaking change, on release, or right after release

Example:

- Initial version: major 0 minor 0 (0.0)
- New stuff added in development: still 0.0
- Release A: 0.1
- Commit right after release: 0.2
- Some more stuff: still 0.2
- Breaking change to how stuff is stored in the RIQ: 1.0
- Some more stuff: still 1.0
- Release B: 1.1
- Commit right after release: 1.2
etc.

This will mean that

- RIQs made with the stable release A or B can't be used with older development versions
- RIQs made with development versions can't be opened by the stable release that came before them
- RIQs made before the breaking change will still be compatible with future versions, but will need an extra conversion step
- RIQs made after the breaking change won't be usable by any previous version, stable or development

**Comment by Saraistupid** [comment]
> RIQs made with development versions can't be opened by the stable release that came before them

Why though? What if the changes aren't breaking?

**Comment by minenice55** [comment]
there already is a version field but we don't read it yet

**Comment by minenice55** [comment]
current chart version is planned to use 
https://github.com/RHeavenStudio/HeavenStudio/blob/28a621b90d7864be4c9c16caff30f123d67a9434/Assets/Scripts/BeatmapFormats/DynamicBeatmap.cs#L25-L29 
these are likely to be assigned using the app bundle ID?
an "application id" field may also be of use for other apps that use our format
