### ISSUE TITLE
mr. upbeat import problem

### ISSUE THREAD

**Issue by dirt-bee** [RHeavenStudio/HeavenStudio#305]
whan importing a file with mr.upbeat, mr upbeat doesn't step.
![Screenshot_2](https://user-images.githubusercontent.com/115891182/220399706-c0374862-7140-4cd3-8e44-c1f27a0abf0c.png)
not sure if its just my pc or not.

**Comment by patataofcourse** [comment]
can i have an example riq for reproducing this?

**Comment by dirt-bee** [comment]
> can i have an example riq for reproducing this?

yes, it might be because of its old age but i found it on
https://www.mediafire.com/file/4hgrd28owezcix4/karat.riq/file
on the 177th beat

**Comment by dirt-bee** [comment]
> compatibility problem issue with very old RIQ files, may be fixed for release via entity conversion?

Probably happens with we writes of games
