### ISSUE TITLE
space ball costume problem

### ISSUE THREAD

**Issue by dirt-bee** [RHeavenStudio/HeavenStudio#306]
if you change from bunnysuit/spherehead back to the standard costume, the batter looks like this:
![ball](https://user-images.githubusercontent.com/115891182/220401358-6606ad76-4341-4d46-88eb-3712a2e26e7c.png)
![bunny](https://user-images.githubusercontent.com/115891182/220401401-c0740b48-d7c7-45e6-a71c-dfae1a7c1f38.png)

**Comment by patataofcourse** [comment]
is this with latest nightly?

**Comment by dirt-bee** [comment]
yes.

**Comment by Rapandrasmus** [comment]
This is also fixed
