### ISSUE TITLE
Opening preview on a wider-than-16:9 aspect ratio freezes the right and left edges of the screen

### ISSUE THREAD

**Issue by blank3times** [RHeavenStudio/HeavenStudio#337]
This was not an issue before 8 March, I have not downloaded any builds between 7 March and 10 March. Currently the latest Windows prebuild.

It's all normal until you enter the preview after which it's frozen on the edges until you open the preview on 16:9 again. Does not depend on game.

https://user-images.githubusercontent.com/105398129/224505259-d1fec0e8-c17f-4f55-8820-3f2becf051f2.mp4
Before, on the normal aspect ratio

https://user-images.githubusercontent.com/105398129/224505353-a83c7fdf-687c-45d6-a805-74d500402172.mp4
I didn't test it with taller, but it definitely happens when it's wider.

https://user-images.githubusercontent.com/105398129/224505399-368077bc-5947-4aa7-8cc5-25e676b93c65.mp4
Back to the 16:9, note it returns to normal only after you preview again.

This is not that it's rendering too wide, as you can see from the monkey placements.

**Comment by minenice55** [comment]
fixed with #340

**Comment by blank3times** [comment]
Ooh, looks fancy, more than just a bugfix!
