### ISSUE TITLE
Will beat city games be added?

### ISSUE THREAD

**Issue by dirt-bee** [RHeavenStudio/HeavenStudio#359]
this sounds stupid, but will you ever add beat city games? cuz if we are doing this with mobile ripoffs... (i know the answer is most likely no)

**Comment by Saraistupid** [comment]
no

**Comment by Starpelly** [comment]
Kind of a bit rude eh?

Anyway, the answer is a solid probably not. If you want beat city games to be added, you can add them yourself @ https://rheavenstudio.github.io/docs-contributing/intro.

This all depends on what people want to make and at what time.
