### ISSUE TITLE
Double Date is unfinished

### ISSUE THREAD

**Issue by Baconhareiscool12345** [RHeavenStudio/HeavenStudio#375]
when i play double date, the soccerball/basketball/football arent showing

**Comment by blank3times** [comment]
Can confirm on Windows. Same thing used to happen with the shuttlecock for air rally.

May be related to the unity thing, as other spirtes recently started breaking (specifically, lauch party launchpad disappeared, and the OK Don't Mind open books don't disappear and stay on screen). I can list those separately if you want, although I'm guessing these issues are related as they all popped up at the same time. =]

**Comment by Baconhareiscool12345** [comment]
PR? I'm not sure what that is...

**Comment by patataofcourse** [comment]
Not a bug, just not implemented yet (Double Date is a WIP)

**Comment by blank3times** [comment]
Alright, I'll put in a new issue then. Thank  you! =]
