### ISSUE TITLE
Suggestions for improving Heaven Studios

### ISSUE THREAD

**Issue by YOU9725** [RHeavenStudio/HeavenStudio#376]
People here are in trouble. They skip updates, neglect to address bugs, and think only of themselves. I think the number of downloads will decrease if this continues. Also, what's up with the red crosses only on the Windows builds? I won't download anymore. Fuck you, you son of a bitch.

**Comment by Saraistupid** [comment]
Please join the discord server for further contact: https://discord.gg/5rdEq2SFNj
We need your great ideas to know how to improve our project as soon as possible.
