### ISSUE TITLE
Lockstep stepping activates slightly before beat for player

### ISSUE THREAD

**Issue by blank3times** [RHeavenStudio/HeavenStudio#394]
(Latest build for Windows)

Player's stepswitcher and sfx are slightly before the defined beat, which can be noticed by playing on 0.25x speed with the metronome and autoplay on. Other stepswitchers move on time with the metronome, leading to both visual and audio offset.

Does not seem to be lag as it is both consistent, and is something earlier as opposed to later.

My recording doesn't seem to work right now (sorry), but I have a screenshot with autoplay paused right before the actual beat to show a setup and what it may look like.
![image](https://user-images.githubusercontent.com/105398129/232705000-0c427f10-1e71-4324-9635-fb75c0cff257.png)
Also not related to the song, there is no song, only metronome.

**Comment by minenice55** [comment]
assigning to @Rapandrasmus

**Comment by minenice55** [comment]
closed by #501

**Comment by blank3times** [comment]
Still an issue after #501 despite rework of how the blocks are laid out; please reopen. Uploading video footage momentarily.

**Comment by blank3times** [comment]
https://github.com/RHeavenStudio/HeavenStudio/assets/105398129/8a4816d0-8ab5-4a71-969d-b0fb120ff4b2

Latest nightly build. Right after booting up and a new way to reproduce.

**Comment by Rapandrasmus** [comment]
The offset between the other steppers and players was reduced in the rework, it was not completely removed. But it was reduced to the point that I think it's unnoticeable. It went from being laggy as hell on my pc to buttery smooth. So I think this post should remain closed.

**Comment by blank3times** [comment]
Very well. I still think it's strange that the sound is before, however if you say it's much improved then I can take that.
