### ISSUE TITLE
Manual Play mode only works for some games

### ISSUE THREAD

**Issue by Joeswano** [RHeavenStudio/HeavenStudio#402]
If you turn the perfect mode off, it seems like only a few games respond to button inputs. The only one that has worked for me so far was Karate Man, in which Karate Joe will punch with the A and S keys. Any other game that I have tested does not work. I can't connect any of my USB controllers either, so I'm stuck with the keyboard.

**Comment by minenice55** [comment]
A key and S key are bound to DPad Left and DPad Down respectively, both allowing a punch input in Karate Man

the full keymapping is the following (this will be properly shown somewhere in the program in a future release)
J = East Face Button (Nintendo A)
K = South Face Button (Nintendo B)
WASD = DPad Directions

**Comment by patataofcourse** [comment]
closing this as invalid; seems like it was just confusion over the controls
