### ISSUE TITLE
Using Ctrl + s to save does not work, only Save As

### ISSUE THREAD

**Issue by Joeswano** [RHeavenStudio/HeavenStudio#408]
It's not just that nothing indicates the save, I remember talking to someone and they mentioned that. It's supposed to save despite not having any pop-up or message confirming that it has saved. But it doesn't save at all for me. I've tested it with multiple files, and the only time any changes actually save is when I use either the Save As button or the shortcut. Since using this I've just overwritten my files using Save As every time I'm finished for the day

**Comment by Saraistupid** [comment]
What OS are you on?

**Comment by minenice55** [comment]
fixed by #463
