### ISSUE TITLE
Mr. Upbeat won't work on on-beat rhythms

### ISSUE THREAD

**Issue by Firerise9402** [RHeavenStudio/HeavenStudio#419]
### Describe the bug

When attempting to use Mr. Upbeat so that each input is on a whole beat of the song, it always is off-beat. It will stay on half-beat rhythms, and swapping to Mr. Downbeat also does not change this.

### How to reproduce the bug?

Use the most recent binary and attempt to use Mr. Upbeat with the inputs on whole beats. .25 speed will help when timing the inputs if needed.

### What Operating System(s) were you using?

Windows 10/11

**Comment by Firerise9402** [comment]
Makes sense. It's much more useful to have it work on-beat as well as off-beat, but at the same time it being faithful to the original would mean it can only be off-beat.

**Comment by minenice55** [comment]
mr downbeat is like a meme lmao

**Comment by blank3times** [comment]
> if you're gonna try and make them on the onbeats you may as well use another ktb game like lockstep or smth

But the beeping =[ /s

**Comment by Captninja6** [comment]
> Just noticed in the docs it says that it should only be used on off-beat. Sorry about that. However, if it's not already planned, could there be a way to use it on-beat? I think it could greatly increase the versatility of the minigame.

Before the newest build you were literally able to use it on the on-beat. They intentionally removed it because the game is only supposed to be on the off-beat

**Comment by RaffyTaffy14** [comment]
am i crazy or is there literally a toggle to disable forcing it to be on-beat when right-clicking the block

**Comment by AstrlJelly** [comment]
it was a last minute thing i threw in that really just doesn't work cuz i made the game based on how the game works instead of. Mr. Downbeat

**Comment by RaffyTaffy14** [comment]
other games like tunnel or marching orders are only ever on the beat, but those don't force you to be onbeat. I'd say the big "issue" is that people were unknowingly using Mr. Upbeat wrong by putting it directly on the beat as you would with any other game but having it but all off because a certain someone's goofy use of prefunctions

**Comment by Rapandrasmus** [comment]
@RaffyTaffy14 this is what happens when people yell at me to fix a game i do not give a fat shit about

**Comment by RaffyTaffy14** [comment]
@Rapandrasmus so what happens
