### ISSUE TITLE
how to start the game?

### ISSUE THREAD

**Issue by Shmops4325** [RHeavenStudio/HeavenStudio#434]
### Describe the bug

I checked the entire "HeavenStudio-master" folder
There are no programs there, only folders and files.
So how do you run it then?

### How to reproduce the bug?

-

### Screenshots/Videos

-

### What Operating System(s) were you using?

Windows 10/11

**Comment by Starpelly** [comment]
read the README

![image](https://github.com/RHeavenStudio/HeavenStudio/assets/24588691/e49ed7c3-27b6-43d6-8062-ba225590e6c7)
