### ISSUE TITLE
DJ School broken on scratch-o

### ISSUE THREAD

**Issue by JackChestnut** [RHeavenStudio/HeavenStudio#447]
### Describe the bug

In version 504d0fae DJ School's scratch-o is broken

### How to reproduce the bug?

Just add scratch-o in, the preview is bugged and the sound is messed up.

### Screenshots/Videos

![图片](https://github.com/RHeavenStudio/HeavenStudio/assets/54014084/5588120a-5659-4851-b17e-bda1e9f4c23e)

### What Operating System(s) were you using?

Windows 10/11

**Comment by AmericanMark** [comment]
This bug is already being worked on by someone (I think it's AstrlJelly). But it's good to know that other people are having this issue too. 

By the way, if you can, can you send a log file or riq?

**Comment by AstrlJelly** [comment]
fixed in my draft pr, just working on finishing up the marching orders rework before i undraft it

**Comment by AmericanMark** [comment]
@AstrlJelly 
Can you attach your PR to this post when it's ready to merge?

**Comment by patataofcourse** [comment]
should be as easy as adding "fixes #447" in the description
