### ISSUE TITLE
Marching Orders is Literally Broken

### ISSUE THREAD

**Issue by AmericanMark** [RHeavenStudio/HeavenStudio#452]
### Describe the bug

Most things in Marching Orders behave abnormally. The marching feature just has one march and ends, the bops don't work. The cadets do not follow the animations. The Background can't change colors, and overall, the game is pretty much unusable.

### How to reproduce the bug?

Use any action in Marching Orders lmao. 

### Screenshots/Videos

https://github.com/RHeavenStudio/HeavenStudio/assets/132851151/d4c9b076-912d-42a7-a67a-b39717302a51

### What Operating System(s) were you using?

Windows 10/11

### Extra files

[Player.log](https://github.com/RHeavenStudio/HeavenStudio/files/11645470/Player.log)
Here is the log file for me testing out the new version of HS.

### Additional context

Latest version of Heaven Studio, played on Windows 11. And yes, I did reinstall the program to make sure it wasn't on my end.

**Comment by AstrlJelly** [comment]
this was fixed 👍

**Comment by saladplainzone** [comment]
Reopening, game is still bugged. Force Maching triggers on every frame

**Comment by saladplainzone** [comment]
wait replying doesnt reopen the issue what

**Comment by minenice55** [comment]
yeah a maintainer has to open it separately
also this can stay closed #458 has a fix

**Comment by AmericanMark** [comment]
Yeah, keep this closed. This was made when the update was first released. 
Everything works as intended now (At least to my knowledge)
