### ISSUE TITLE
Large music files aren't loaded

### ISSUE THREAD

**Issue by KLONOA9X6** [RHeavenStudio/HeavenStudio#468]
### Describe the bug

When Heaven Studio in the game scene, press Esc can't pause the game

### How to reproduce the bug?

1. Open a RIQ file with Heaven Studio.
2. Press Esc key.

### What Operating System(s) were you using?

Windows 10/11

### Additional context

Heaven Studio version: [3425052](https://github.com/RHeavenStudio/HeavenStudio/commit/3425052a983fb8fc38db4b70770cf076048f670a)

**Comment by ThatZeoMan** [comment]
This bug report is incredibly vague and nearly impossible for developers to track down the issue. More detail (especially a screen recording showing you opening Heaven Studio) would be very helpful.
I'll try to help you here. Is there an End Remix event in the RIQ? Did you open the RIQ with Heaven Studio, or did you load it through the editor?

**Comment by KLONOA9X6** [comment]
> This bug report is incredibly vague and nearly impossible for developers to track down the issue. More detail (especially a screen recording showing you opening Heaven Studio) would be very helpful. I'll try to help you here. Is there an End Remix event in the RIQ? Did you open the RIQ with Heaven Studio, or did you load it through the editor?

https://github.com/RHeavenStudio/HeavenStudio/assets/95112579/131e318d-1d2b-46a7-933b-dd827080781b

**Comment by minenice55** [comment]
need a log file to identify issue

**Comment by KLONOA9X6** [comment]
> need a log file to identify issue

I think it's useless to provide a log file because program running with no error (except for the font issue)
https://pastebin.com/6cr7fkZE

**Comment by minenice55** [comment]
says chart has no music which may lead to issue

**Comment by minenice55** [comment]
found "issue"
https://github.com/RHeavenStudio/HeavenStudio/blob/3425052a983fb8fc38db4b70770cf076048f670a/Assets/Scripts/GameManager.cs#LL554C9-L554C9
in play mode charts won't play if no music exists (generally indicative of "failed to load" but charts with no music *could* exist)
need to add behaviour to handle that edge case

**Comment by KLONOA9X6** [comment]
> in play mode charts won't play if no music exists (generally indicative of "failed to load" but charts with no music could exist)
need to add behaviour to handle that edge case

In fact, even if there is music, the chart will not play

https://github.com/RHeavenStudio/HeavenStudio/assets/95112579/c41de7e5-9338-4928-b8b1-b1c0a37c17ab

**Comment by minenice55** [comment]
hm it's possible that nonstandard symbols in paths break loading, will test

**Comment by minenice55** [comment]
error message is logged from here which runs if the path to the cached audio file is not found / invalid:
https://github.com/RHeavenStudio/HeavenStudio/blob/3425052a983fb8fc38db4b70770cf076048f670a/Assets/Scripts/GameManager.cs#LL193C20-L193C20
may I see what the path to the temporary cache looks like on your system?

### steps to get to the temporary cache:
- open a chart in play mode (so that the cache can be created)
- hit Win + R
- enter `%temp%\RHeavenStudio\Heaven Studio\RIQCache`

make a screenshot or copy/paste the path to here. (remember to remove sensitive data)

**Comment by KLONOA9X6** [comment]
> make a screenshot or copy/paste the path to here. (remember to remove sensitive data) or let me know if you can't find the folder
![image](https://github.com/RHeavenStudio/HeavenStudio/assets/95112579/882a8748-4c30-4c23-9ab5-0e25a766d05b)

**Comment by minenice55** [comment]
is it OK if you copied the whole URL from the address bar to here? (if there's private info it's fine if you don't)

**Comment by KLONOA9X6** [comment]
> is it OK if you copied the whole URL from the address bar to here? (if there's private info it's fine if you don't)

It's OK, this is the RIQ file that I used

**Comment by minenice55** [comment]
I mean like this, so I could see the whole thing (just want to check if there's non-ascii in the path or something)
![image](https://github.com/RHeavenStudio/HeavenStudio/assets/43734252/e12510ef-bd3c-4f1e-9234-0e931fbd5025)

**Comment by KLONOA9X6** [comment]
> I mean like this, so I could see the whole thing (just want to check if there's non-ascii in the path or something, don't mind the Jukebox folder name it's a development path) ![image](https://user-images.githubusercontent.com/43734252/245349076-e12510ef-bd3c-4f1e-9234-0e931fbd5025.png)

![image](https://github.com/RHeavenStudio/HeavenStudio/assets/95112579/d0c4f644-8e98-481f-af7c-1a97ba908b1f)

**Comment by minenice55** [comment]
ok yeah I see what could be going on, will do some testing and see if a fix can be made

**Comment by minenice55** [comment]
found the issue, had to do with large music files actually
unity would try to download the entire music file despite being told to stream it, I adjusted some conditions in Jukebox to only initially download a smaller chunk
this issue will be fixed in Heaven Studio shortly

**Comment by KLONOA9X6** [comment]
Well done, but my original issue was still unresolved

**Comment by KLONOA9X6** [comment]
Well done, but my original issue was still unresolved (Press Esc key and pause menu didn't appear)
Also a new problem #475
