### ISSUE TITLE
Munchy Monk cannot work properly

### ISSUE THREAD

**Issue by KLONOA9X6** [RHeavenStudio/HeavenStudio#475]
### Describe the bug

"One", "Two Two", "Three" events did nothing.

### How to reproduce the bug?

1. Open Heaven Studio
2. Drag "One" event to track
3. You'll see the bug

### Screenshots/Videos

https://github.com/RHeavenStudio/HeavenStudio/assets/95112579/41c7bf8c-e11f-426f-91a9-d46d903dd017

### What Operating System(s) were you using?

Windows 10/11

### Log file

```shell
https://pastebin.com/LYDU2U6w
```

### Additional context

Heaven Studio version: [534b063](https://github.com/RHeavenStudio/HeavenStudio/commit/534b06301dc9deeb8638553265ca5a5c49a1c41a)

**Comment by Davizinhn** [comment]
#476 
fixed here

**Comment by AstrlJelly** [comment]
this is a problem with asset bundles; the script that builds the prebuilt binaries doesn't build them correctly. your check for if the cloud monkey is null would work, but just properly assigning it in the game would work better. i'll pr some editor stuff today that will have built asset bundles, which will fix this.
