### ISSUE TITLE
Working Dough won't allow for a gap between turns of less than 3/4ths of a beat.

### ISSUE THREAD

**Issue by Firerise9402** [RHeavenStudio/HeavenStudio#477]
### Describe the bug

For some reason, when using working dough, if the pass turn block is less than 3/4ths of a beat from the end of an interval, the turn will not be passed.

### How to reproduce the bug?

Create an interval with working dough and try to pass the turn either a quarter beat, a half beat, or immediately after the end of the interval. I'm not sure if this is intentional or not, considering it could be a safeguard to keep a map from being too hard, but on slower maps it could be a huge problem to work around.

### What Operating System(s) were you using?

Windows 10/11

**Comment by Rapandrasmus** [comment]
Pass turn is intended to placed at the end of the start interval block

**Comment by Firerise9402** [comment]
Update: Pass turn does work half a beat after the interval ends, just not a quarter beat.

**Comment by Firerise9402** [comment]
Wait hang on. I'm very confused. I do something like this:
![image](https://github.com/RHeavenStudio/HeavenStudio/assets/90978630/d8f06edb-2206-4492-9f80-4f71f8505b92)
and the first small ball registers and gets passed, but the second doesn't because it's half a beat away.
Also scratch that update it was wrong.

**Comment by Rapandrasmus** [comment]
This is only if the start interval block is like under 2 beats long which you should never put it as, I wish one was able to limit how much you can stretch a block.

**Comment by Firerise9402** [comment]
Ok now I'm even more confused because this works fine and passes all of the notes:
![image](https://github.com/RHeavenStudio/HeavenStudio/assets/90978630/2c2757d0-3704-4321-929c-968ac1aa78e9)
But the other one doesn't, with the same gap and everything.

**Comment by Rapandrasmus** [comment]
Also start interval shouldn't be stretched according to each input, it should be stretched according to the length of the interval.

**Comment by Firerise9402** [comment]
> Also start interval shouldn't be stretched according to each input, it should be stretched according to the length of the interval.

What do you mean by this? I'm not exactly following.

**Comment by Firerise9402** [comment]
Got it, thanks!

**Comment by Firerise9402** [comment]
Ok, so after a bit of testing I noticed that trying to fix the map, having a pass turn close enough to a ball still won't pass the turn as  in the original issue, regardless of the interval's length or anything. Am I missing something?

**Comment by Rapandrasmus** [comment]
What does the full interval look like

**Comment by Firerise9402** [comment]
If I'm limiting the size just to the starting block and input, it's this:
![image](https://github.com/RHeavenStudio/HeavenStudio/assets/90978630/1b463098-7a08-4987-9c37-eae9dbd40941)
But I have some room to stretch the start interval block (1 beat on each side). However, that does nothing to help.

**Comment by Rapandrasmus** [comment]
You should never do this??

**Comment by Firerise9402** [comment]
Fair enough, I should probably nerf that part a bit. The main reason I'm doing that is because the song is supposed to be extremely hard. I did also chart that a while ago, so it would be helpful to rechart that a bit.

**Comment by Rapandrasmus** [comment]
Please don't use call and response games like this. Use something like karate man if ur basically just doing 1 beat cues

**Comment by Firerise9402** [comment]
Fair. I've combined the part that happens before that and this part to make it more normal, like this:
![image](https://github.com/RHeavenStudio/HeavenStudio/assets/90978630/04d5b379-efc7-4bb2-9fb4-349bc6433bd9)
