### ISSUE TITLE
Broken Editor

### ISSUE THREAD

**Issue by Amy54Desu** [RHeavenStudio/HeavenStudio#481]
### Describe the bug

I'm encountering odd bugs with the editor, I'm not sure what's happening but the editor is having major problems, whether it be with doing things like deleting volume changes (with them still remaining), saving not working correctly, new game not clearing the previous game or loading a remix not loading it correctly

### How to reproduce the bug?

I just use the editor as normal really. These bugs happen and I have no idea what causes it

### Screenshots/Videos

Here is the Volume Editor glitching out due to it not being deleted properly

https://github.com/RHeavenStudio/HeavenStudio/assets/69287652/1b241d3e-0c6e-41ad-a379-268638c1247e

### What Operating System(s) were you using?

Windows 10 x64

### Log file

[Player-prev.log](https://github.com/RHeavenStudio/HeavenStudio/files/11777811/Player-prev.log)
[Player.log](https://github.com/RHeavenStudio/HeavenStudio/files/11777812/Player.log)

### RIQ file

OOPS WE DON'T SUPPORT THAT FILE TYPE
![image](https://github.com/RHeavenStudio/HeavenStudio/assets/69287652/de647d82-b994-44ba-a983-ab29b39a8014)

### Additional context

This remix was made with the latest version, it is not an old remix, and the previous version of this remix which I made using an older version of the editor I recall did not have these odd bugs happen. Also the cue deletion failing can also cause things like having volume changers overlap which is not normally possible

**Comment by patataofcourse** [comment]
mind uploading the riq inside a zip?

**Comment by Amy54Desu** [comment]
> mind uploading the riq inside a zip?

staff roll is the new one, now I'm encountering a problem that if I change where it starts, the music offset breaks
[sm64_staff_roll.zip](https://github.com/RHeavenStudio/HeavenStudio/files/11783441/sm64_staff_roll.zip)
[tama_negi_sensei_remix_d_2.zip](https://github.com/RHeavenStudio/HeavenStudio/files/11783445/tama_negi_sensei_remix_d_2.zip)

**Comment by MetalAshura** [comment]
flan. i also have dealt with the same offset issue aswell with 2 of my wip custom remixes
