### ISSUE TITLE
The whole editor doesn't work on M1 and Intel Macs

### ISSUE THREAD

**Issue by poachedegg12** [RHeavenStudio/HeavenStudio#495]
### Describe the bug

A few issues i've had trying to make a remix on my m1 mac:
- Can't create a new remix
- Can't open a remix
- Can't save a remix
- Can't select music
- None of the games render (at all)
- Can't 'stop' the remix while it is playing (preventing further editing)
- Can't undo/redo
- Probably some more issues somewhere

### How to reproduce the bug?

1. Download the editor on Mac
2. Open the editor
3. Try to make a remix

### Screenshots/Videos

[video.mov.zip](https://github.com/RHeavenStudio/HeavenStudio/files/11923721/video.mov.zip)

### What Operating System(s) were you using?

macOS

### Log file

```shell
See 'extra files' (log is too long to put here)
```

### RIQ file

Can't save to file

### Extra files

[Player.log](https://github.com/RHeavenStudio/HeavenStudio/files/11923727/Player.log)

### Additional context

Confirmed to be a problem on M1 and Intel processors

**Comment by minenice55** [comment]
issue with current JSL build, dev branch currently in development uses newer builds that should fix this

**Comment by poachedegg12** [comment]
Where can I download these builds?

**Comment by minenice55** [comment]
currently in development, adding tracking branch

**Comment by poachedegg12** [comment]
cool, thanks for the help

**Comment by LeWolfYT** [comment]
i have an intel mac, and I experience the same symptoms.

**Comment by poachedegg12** [comment]
It's been a while since I last tried using the editor on Mac but everything seems to be working fine now.
