### ISSUE TITLE
flashing screen

### ISSUE THREAD

**Issue by newJohnnyxd** [RHeavenStudio/HeavenStudio#496]
### Describe the bug

Despite the fact that the editor works perfectly, it can be played correctly, the screen where all the assets are seen looks red with some intermittence, which is a bit annoying for the eyes

### How to reproduce the bug?

From the beginning, when you start using the editor, the screen looks like this flashing even if you change the game, Although this only happens on the small screen, when it is full screen it does not happen

### Screenshots/Videos

![Captura de pantalla 2023-07-04 115424](https://github.com/RHeavenStudio/HeavenStudio/assets/138614191/dae5239b-11e7-46cd-bb2c-9e675d8a9316)

**Comment by ThatZeoMan** [comment]
Please provide a log & riq file, otherwise we can’t help
