### ISSUE TITLE
change tempo

### ISSUE THREAD

**Issue by newJohnnyxd** [RHeavenStudio/HeavenStudio#498]
### Describe your suggestion

An option to change the tempo at a certain moment in the song would be quite useful because there are many songs that change the tempo at a certain moment

**Comment by Rapandrasmus** [comment]
Press the icon with the music note and arrow with the tooltip "tempo change" to place down tempo changes

**Comment by Madrel** [comment]
The music note icon under the preview screen is the change tempo option. Also i suggest joining the discord server to ask things about the editor if you're unsure about some things

**Comment by minenice55** [comment]
already implemented
