### ISSUE TITLE
Flipper Flop is sorted chronologically under DS games

### ISSUE THREAD

**Issue by blank3times** [RHeavenStudio/HeavenStudio#537]
A whole form would be extensive.

**I notice that `Assets/Scripts/GamesFlipperFlop/FlipperFlop.cs` says `"ntr"` and not `"rvl"` on line 94 and I'm 90% sure that's the culprit.**

I could fix it myself if I knew how meta files worked and if you need to change them or not. (I also don't have a unity licence to test it) Sorry! If that's literally the whole source of the issue and nothing has to be done to the metas and y'all don't want to do it then I can fix something small like this.

**Comment by Rapandrasmus** [comment]
You mean Rvl not "rev", that's weird zeo musta brainfarted

**Comment by blank3times** [comment]
> You mean Rvl not "rev",

Yes. My brain has shut off.

**Comment by ThatZeoMan** [comment]
> You mean Rvl not "rev", that's weird zeo musta brainfarted

Yeah i messed up lol
