### ISSUE TITLE
Heaven studio games

### ISSUE THREAD

**Issue by upbeatislander** [RHeavenStudio/HeavenStudio#539]
### Is your feature request related to a problem? Please describe.

I need some help of coding

### Describe your suggestion

I want to test out my games

### Describe alternatives you've considered

![144-1446803_paddler-ds-rhythm-rally](https://github.com/RHeavenStudio/HeavenStudio/assets/142502237/b36b8f9e-2c89-40aa-9072-e62f575ee0fe)
![144-1446803_paddler-ds-rhythm-rally](https://github.com/RHeavenStudio/HeavenStudio/assets/142502237/0e9531d0-173b-46a1-8895-7dca0ecdc548)

### Additional context

![1519955_thelamenamejero_donk-donk-fan-made-portrait-art](https://github.com/RHeavenStudio/HeavenStudio/assets/142502237/e0c9213d-2bf0-4aa9-993d-4f2d3d8a0613)
![1519955_thelamenamejero_donk-donk-fan-made-portrait-art](https://github.com/RHeavenStudio/HeavenStudio/assets/142502237/f9de6398-7d7a-47c8-be01-133de7abab20)
![468-4682999_happiness-clipart-bluebird-happiness-rhythm-heaven-megamix-flock](https://github.com/RHeavenStudio/HeavenStudio/assets/142502237/8a9996ab-a263-4f56-acb5-d7f04c6a4a92)
![150-1505690_see-and-saw-see-saw-rhythm-heaven](https://github.com/RHeavenStudio/HeavenStudio/assets/142502237/f73d188f-3502-4637-956e-4a3449e45ce0)

**Comment by Rapandrasmus** [comment]
What?

**Comment by ThatZeoMan** [comment]
what does this mean
