### ISSUE TITLE
Tempo changes after the first one don't work properly

### ISSUE THREAD

**Issue by blank3times** [RHeavenStudio/HeavenStudio#549]
### Describe the bug

Instead of changing to whatever tempo you want, it'll be to the same as the first one no matter what. This makes playing with the tempo much more difficult.

### How to reproduce the bug?

Change the tempo once to something other than the default, then change it to a new number different from the other two and try again after the first change. If the issue happens to you, the number will flicker from the desired tempo to the first changed tempo which is undesired.

### Screenshots/Videos

https://github.com/RHeavenStudio/HeavenStudio/assets/105398129/4adbc318-cea9-4d95-8dc5-25adcbfff3dd

### What Operating System(s) were you using?

Windows 10/11

**Comment by RaffyTaffy14** [comment]
if I remember correctly, that was an intentional change. I have no clue why it was intentional. i despise it and want it to burn in the depths of love rap

**Comment by blank3times** [comment]
>  burn in the depths of love rap
We could make it a question on Quiz Show!

**Comment by minenice55** [comment]
adjusting tempo changes is to be replaced with a completely new UI-based system in the near future

**Comment by blank3times** [comment]
> i was gonna say "burn in the depths of quiz show" but I don't actually hate quiz show

I don't hate any of them *o* (if I had to pick a least favourite it's probably Sick Beats because it might be the only one with absolutely 100% visual requirement, and I like that one too)

**Comment by blank3times** [comment]
As it turns out, it DOES let you do it after, but only if the bpm is slower.
