### ISSUE TITLE
AssetBundles can fail to load 

### ISSUE THREAD

**Issue by dirt-bee** [RHeavenStudio/HeavenStudio#566]
### Describe the bug

i dont know if this is just my computer, but after adding more than a couple games it immedietly starts to break, the screen turns black, space doesent pause, the STOP button doesent work
![prob](https://github.com/RHeavenStudio/HeavenStudio/assets/115891182/fb9e4c05-e842-4bbb-8a03-11e05098e55d)

### How to reproduce the bug?

adding some start games and (maybe) putting the start at the start game

### What Operating System(s) were you using?

Windows 10/11

### Additional context

this pc has alot of problems, it may be the pcs fault.

**Comment by minenice55** [comment]
already fixed in #554, adding tracking branch

**Comment by dirt-bee** [comment]
thanks, ill wait for that patch if its not already done
