### ISSUE TITLE
Github Actions builds for Linux and Mac OS broken

### ISSUE THREAD

**Issue by leftshift** [RHeavenStudio/HeavenStudio#573]
### Describe the bug

[c60cb48](https://github.com/RHeavenStudio/HeavenStudio/commit/c60cb48c8c50af8482805640cdaf916e150b11c1) was the last commit for which the pipeline produced valid linux and mac os builds.

With [3740642](https://github.com/RHeavenStudio/HeavenStudio/commit/3740642d80192334666cb743996704a277d134a8), the action only generated 10KB tar files for the two platforms, although I don't see anything obvious in that commit that might have caused the issue.

### How to reproduce the bug?

-

**Comment by minenice55** [comment]
should be fixed wait for this action to finish
