### ISSUE TITLE
The waveform is not visible

### ISSUE THREAD

**Issue by Erfaniom** [RHeavenStudio/HeavenStudio#576]
### Describe the bug

The waveform doesn't show up where its supposed to be

### How to reproduce the bug?

add any music and the waveform doesn't show up

**Comment by Starpelly** [comment]
lmao

**Comment by Starpelly** [comment]
> According to the Heaven Studio Discord, the waveforms feature was removed due to the previous implementation of it being sloppy. It will be re-added in a future update.
> 
> > lmao
> 
> Please don't be rude.

lmao

**Comment by minenice55** [comment]
feature to be re-implemented in future release
