### ISSUE TITLE
Heaven Studio "Not Supported" on my Mac.

### ISSUE THREAD

**Issue by TheBoardGitOfFun-Official** [RHeavenStudio/HeavenStudio#594]
### Describe the bug

When I try to launch Heaven Studio, it shows a dialog saying "You can't open the application 'Heaven Studio' because this application is not supported on this Mac.

### How to reproduce the bug?

Use a 2018 Mac mini running macOS Ventura 13.3.

### Screenshots/Videos

![Screenshot 2023-12-13 at 10 08 34 PM](https://github.com/RHeavenStudio/HeavenStudio/assets/139513678/d0f5dcb7-d7d5-4394-bc17-7f9e61bace50)

### What Operating System(s) were you using?

MacOS

**Comment by ThatZeoMan** [comment]
sorry i'm just gonna have to get this out of the way, are you sure you didn't download the windows version 😅

**Comment by TheBoardGitOfFun-Official** [comment]
> sorry i'm just gonna have to get this out of the way, are you sure you didn't download the windows version 😅

yea, i clicked macos and it just seems that it won't work.
