### ISSUE TITLE
Access to the path '/savewav' is denied

### ISSUE THREAD

**Issue by GummyLeeches** [RHeavenStudio/HeavenStudio#603]
### Describe the bug

Upon trying to load a custom music file, I receive the error "access to the path 'savewav' is denied"

### How to reproduce the bug?

See above

### Screenshots/Videos

![error](https://github.com/RHeavenStudio/HeavenStudio/assets/45316605/90062ddd-ba5a-401e-894a-643e3614e4d7)

### What Operating System(s) were you using?

Linux

### Additional context

I am using Arch Linux

**Comment by Hydra2134** [comment]
This is also happening to me on Garuda Linux. I tried both the nightly build and the stable build.

**Comment by Hydra2134** [comment]
Ah, the song needs to be a .wav file, then it works.
