### ISSUE TITLE
Sound stutters

### ISSUE THREAD

**Issue by AnonymousPerson607** [RHeavenStudio/HeavenStudio#617]
### Describe the bug

When I'm making a remix, the sound just starts stuttering. Not sure if it's a problem with my PC though.

### How to reproduce the bug?

1. Open HS
2. Go to create
3. Add a file/create a remix
4. Preview your remix

### Screenshots/Videos

https://github.com/RHeavenStudio/HeavenStudio/assets/76531627/e76f720b-62f8-4cb8-9b08-b1d248539347

### What Operating System(s) were you using?

Windows 10/11

### Additional context

It also happens in the title screen

**Comment by minenice55** [comment]
in settings try increasing the size of the audio buffer until it's more stable (larger values are more stable but increase latency)

**Comment by AnonymousPerson607** [comment]
> in settings try increasing the size of the audio buffer until it's more stable (larger values are more stable but increase latency)

do you mean the DSP buffer size? if so, it's already at the max and it still stutters
