### ISSUE TITLE
Games

### ISSUE THREAD

**Issue by heavenstudiohype** [RHeavenStudio/HeavenStudio#621]
### Is your feature request related to a problem? Please describe.

Take a break from making custom remixes and play rhythm games!
Built in Games like
Monkey Watch, Rotation Sushi, Rhythm Cannery, or even Splashdown! A remix is at the end.
As of Stage 7, they will start arrangin'
Also, some minor tweaks
See-Saw does not have the infamous ending cutscene, just some more beats till it fades to black
Do not make clusters of holes in Punch Holes
Remix 10 should be a medley remix
Also, upload or draw your own epilogues and title cards!
Play other players' remixes!
Report remixes if they break the HS rules.

### Describe your suggestion

Look on the past message!

The features should be added to release 3 (Machine).

### Describe alternatives you've considered

Custom Game & Custom Remix Mix & Match
Make custom full games with your custom games & remixes!
When making a new project, they will choose questions
Which one will you create?
What engine would you use?
Will you engine edit?

Put full games online for up to 10 stages!
Starting a full game plays an animation of a cartridge getting put into a console and lots of RH characters get sucked into it before starting. Some may be scared, some may be happy, and some may not care! (The characters not only appears in official ones (agb, ntr, rvl, ctr), but also unofficial ones! (pco, mob)

The custom Prologue editor currently has 3 fonts:
https://fontworks.co.jp/fontsearch/kurokanestd-eb/  (Kurokane),
https://fontworks.co.jp/fontsearch/slumpstd-db/  (Slump),
and https://fontworks.co.jp/fontsearch/cometstd-b/ (Comet).

### Additional context

How will you make 60+ games in 1 day?

I like accepted ideas.
Way to nail the editing!

==Superb==
you got a medal!

You guys can make it bc I am only good at scratch

<img width="1059" alt="Screenshot 2024-01-06 at 9 36 03 AM" src="https://github.com/RHeavenStudio/HeavenStudio/assets/156635279/caf510e0-efb9-42ac-bfe3-a52d4def8e29">

An unused asset, but play the quiz it is linked to!
https://www.sporcle.com/games/lucasolsont/guess-the-rhythm-heaven-game-by-japanese-name-2

Made by me!

**Comment by heavenstudiohype** [comment]
This can make Heaven Studio more "playful"

**Comment by AstrlJelly** [comment]
oh my god

**Comment by blank3times** [comment]
For starters you can change the epilogue image already o_o

**Comment by heavenstudiohype** [comment]
<img width="480" alt="Screenshot 2023-12-23 at 8 41 03 PM" src="https://github.com/RHeavenStudio/HeavenStudio/assets/156635279/0bb89762-e0ed-4752-ad59-6e08fb5e8e94">
"You can never have TOO MANY widgets!"

**Comment by heavenstudiohype** [comment]
I meant an "Advanced epilogue maker"

**Comment by heavenstudiohype** [comment]
In the custom prologue maker, if your text contains a "Notdef" in the font, it will show an error.

**Comment by heavenstudiohype** [comment]
![Congarts!_(Enter_your_Name)](https://github.com/RHeavenStudio/HeavenStudio/assets/156635279/375fd771-dbf5-407a-9816-58501625480e)
Usernames like this on this keyboard could happen, imagine users that only use game icons in their name

**Comment by blank3times** [comment]
What if you make all of this on scratch.

**Comment by Squiddu** [comment]
nah what arcade game is that photoshop thingamabob stolen from

**Comment by heavenstudiohype** [comment]
isn't this a C# project?

**Comment by Squiddu** [comment]
uh.. whuh??? what???

**Comment by heavenstudiohype** [comment]
Earn medals, earn endless games and

**Comment by heavenstudiohype** [comment]
rhythm toys!

**Comment by heavenstudiohype** [comment]
Make you own challenge train editor (The monster looks too scary when the game is eaten)
Think of a new goal

**Comment by heavenstudiohype** [comment]
tengoku arcade

**Comment by RaffyTaffy14** [comment]
do you want me to call a medical specialist

**Comment by heavenstudiohype** [comment]
<img width="1280" alt="Screenshot 2024-01-09 at 4 29 26 PM" src="https://github.com/RHeavenStudio/HeavenStudio/assets/156635279/ab3a7015-497a-4a2d-b547-aa89dd61bbcd">
something I made on Roblox Spray Paint

**Comment by RaffyTaffy14** [comment]
nice!

**Comment by Squiddu** [comment]
my good digital fellow this is a heaven studio issue

**Comment by RaffyTaffy14** [comment]
i think he's the one having the issue not the program

**Comment by Squiddu** [comment]
therapy studio

**Comment by heavenstudiohype** [comment]
"Do not make clusters of holes in Punch Holes"
this one is for people with trypophobia

**Comment by RaffyTaffy14** [comment]
heavenstudiohype tell me your issues
![image](https://github.com/RHeavenStudio/HeavenStudio/assets/105959219/e0e5725e-46c3-419f-b026-aea1ad511ca9)
