### ISSUE TITLE
Make Rockers (DS) use Big Rock Finish (3DS) controls

### ISSUE THREAD

**Issue by User670** [RHeavenStudio/HeavenStudio#626]
### Is your feature request related to a problem? Please describe.

it's more intuitive that way.

### Describe your suggestion

Make it "press to play, release to mute" instead of "release to play, press to mute".

**Comment by blank3times** [comment]
It would be very difficult to do the muting tap (such as what you see on the 2nd cue for rockers 2 in the original)
