### ISSUE TITLE
Offset calibration

### ISSUE THREAD

**Issue by User670** [RHeavenStudio/HeavenStudio#627]
### Describe your suggestion

Add some form of offset calibration. A calibration wizard would be nice, but a simple slider / text box would suffice.

### Additional context

I know minenice on discord already said you are not doing it (the reason being "hitsounds are keysounds" and adding an offset makes it sound bad), but this comes at a cost of player's experience?

Some rhythm games (like osu!) just don't care and let you calibrate anyway. A few rare cases (Rhythm Doctor) will play the hitsound on beat regardless of your input (and will play an additional miss sound after the hit window passes), but I suppose this might not work out well for Rhythm Heaven (graphics and game logic sometimes heavily depend on whether you hit or miss).

**Comment by ThatZeoMan** [comment]
Rhythm heaven fundamentally does not work with calibration. the visual animation of all minigames means that video, audio, and input offset just does not work with rhythm heaven.  the best we can do is to reduce latency as much as possible, similar to Bits & Bops. Sorry! 🙏
