### ISSUE TITLE
question + feature = this

### ISSUE THREAD

**Issue by heavenstudiohype** [RHeavenStudio/HeavenStudio#629]
### Is your feature request related to a problem? Please describe.

what is your favorite event/cue

### Describe your suggestion

Minigame type idea:
BaB (bits and bops)

### Describe alternatives you've considered

it will get 3 games as of now
"Flipper Snapper"
"Hammer Time!"
"Meet and Tweet"

### Additional context

also make Japan, and Korean heaven studio lush release

My favorite cue is
Optic blast
<img width="1280" alt="Screenshot 2024-01-16 at 3 25 08 PM" src="https://github.com/RHeavenStudio/HeavenStudio/assets/156635279/28940a09-f4e5-4010-850a-05cff780de9c">

**Comment by GhostlyGuyGD** [comment]
no
