### ISSUE TITLE
Dazzles animations function strangely with Force Hold

### ISSUE THREAD

**Issue by Seanski2** [RHeavenStudio/HeavenStudio#640]
### Describe the bug

The Dazzles will more often than not cause the miss animation to play after successfully performing a cue after a Force Hold block. Autoplay seemingly does not have this issue.

### How to reproduce the bug?

Attempt to input a cue after a game transition with a force hold.

### Screenshots/Videos

https://github.com/RHeavenStudio/HeavenStudio/assets/65259418/3c38f9d3-d6bb-457d-b58c-57d609570078

### What Operating System(s) were you using?

Windows 10/11

**Comment by oddMLan** [comment]
While it no longer causes the Dazzles to trip over in embarrassment, it still produces a fail sound.
Autoplay doesn't have the issue. Using the 8b71fc22342eea8b94482eca751142142eb7e4df nightly on Win10.
Also, I'm not sure if it's currently allowed, but would it be possible to make posing without holding an option? Autoplay seems to be okay with this.

https://github.com/RHeavenStudio/HeavenStudio/assets/7278372/2126dce9-60ed-42b0-8790-833c1511a939
