### ISSUE TITLE
Mobile Port for those who don't have a PC

### ISSUE THREAD

**Issue by JoelIzDaBest66** [RHeavenStudio/HeavenStudio#644]
### Is your feature request related to a problem? Please describe.

Can you please make a mobile port for those who can't afford/don't have a PC? It would help out.

### Describe your suggestion

My computer once broke down and can't run Heaven Studio properly, and it is need of repair, and thus explains why I need a mobile version (an .APK file, to be exact).

### Describe alternatives you've considered

You know, just grab the source code and make a mobile version for it. Port it to an .APK file (.IPA file for iOS users) and publish it in itch.io.

### Additional context

The controls must be accurate to the DS controls, even for games that are not in the DS. It requires using your thumb/other types of fingers, but the controls MUST be unique (for example, Sick Beats must include swiping to random directions to kill the virus, Catchy Tune must include directional taps, and Octopus Machine must be controlled like the DS version).

**Comment by saladplainzone** [comment]
Not currently planned, sorry. Would be too difficult to maintain alongside the PC releases.

**Comment by ThatZeoMan** [comment]
we're an open source project, you shouldn't assume  that every contributor is a "professional game developer" and even if they are, they're not obligated to just do whatever you want. if you think making a mobile port would be so easy, i'm sure you could do it yourself.

**Comment by JoelIzDaBest66** [comment]
...Okay then. I don't know what else to say, so yeah.

**Comment by ryanabx** [comment]
It should be noted that for 99% of open source projects, the developers are not being paid to do work, and they typically work on what they choose to work on / what they have the resources and knowledge to work on.

Additionally, mobile ports for games are quite complex depending on the project, for instance Minecraft is developed by a large company and even still it took years for the mobile port to have feature parity to Minecraft. It's not always as simple as adding a joystick to the interface, there's things behind the scenes that must be modified to make a mobile port work :)

I see 2 ways that heaven studio could gain a mobile port:
1. Someone with the proper knowledge and passion comes along and contributes their time to the project free of charge.
2. Someone gets paid to make the feature happen, maybe via donation

**Comment by kkuhn317** [comment]
https://github.com/kkuhn317/HeavenStudio/releases/tag/android1.1

Here's an android port I quickly made, it only supports play mode and has lag issues but I will try to improve it over time.
