### ISSUE TITLE
Visual bugs with Flipper Flop

### ISSUE THREAD

**Issue by AnonymousPerson607** [RHeavenStudio/HeavenStudio#646]
### Describe the bug

Triple flips and flipper-rolls are wonky.

### How to reproduce the bug?

1. Switch game to Flipper Flop
2. Add Triple Flips or Flipper-Rolls
3. Press Space

### Screenshots/Videos

https://github.com/RHeavenStudio/HeavenStudio/assets/76531627/55b5c371-dc74-46c8-9950-882e8539fd16

**Comment by AnonymousPerson607** [comment]
IDK how to change but I'm using Windows 11

**Comment by RaffyTaffy14** [comment]
this is what happens when you stack the roll/triple flip cue on top of the flipping

**Comment by AnonymousPerson607** [comment]
oh ok
