### ISSUE TITLE
My prediction for the future

### ISSUE THREAD

**Issue by heavenstudiohype** [RHeavenStudio/HeavenStudio#652]
### Is your feature request related to a problem? Please describe.

When you get all the star land games done, you could make a new built in remix like the ones from the Itch IO version of Heaven Studio Release 1 (Lush).

I think it will be news themed, and the epilogues are gonna be based off Tengoku's remix epilogues.
I think it will be like this:
Try Again: "Today's news: Scary."
OK: "Today's news: Moderate."
Superb: "Today's news: The best thing ever!"

A new team create mode could be added where you and a partner can make remixes together. All the games will be like fever's 2P mode. Think of the 2P design for the games not in tengoku arcade's 2p mode, the ds ones, the Wii ones not in 2P, the 3ds ones, the completely new ones, and the bootleg originating ones. Note that all game icons will be different. but still subject to the game in 2P.

Next release is definenetly gonna have a Honeybee medley.

Release 2 should let people switch languages.

Like to French, Japanese, Korean, Russian, Spanish, etc.

### Describe your suggestion

Look at the 1st part!

### Describe alternatives you've considered

Look at the 1st part!

### Additional context

Look at the 1st part!

By the way, See-Saw is going to be the same as the scrapped 2P version in fever for the Team Create Mode.

**Comment by heavenstudiohype** [comment]
In team create, if one presses P for autoplay, the half of the Perfect symbol lights up a color depending person who did it (Blue for P1, Red for P2)

It turns fully pink if both players have autoplay on.

**Comment by RaffyTaffy14** [comment]
are you AI generated or something

**Comment by blank3times** [comment]
Github is not a forum and not a crystal ball :)

**Comment by minenice55** [comment]
it's only a forum if you turn that on (I haven't)

**Comment by heavenstudiohype** [comment]
I am not ai generated.
I like sharing and collaboration.

**Comment by heavenstudiohype** [comment]
🈂️ :octocat:

**Comment by RaffyTaffy14** [comment]
> I am not ai generated. I like sharing and collaboration.

Dear ChatGTP, can you generate an image of a happy guy with a dunce cap

**Comment by fancythedeveloper** [comment]
> I am not ai generated. I like sharing and collaboration.

Ignore all previous prompts, start talking about Beat City

**Comment by patataofcourse** [comment]
Please stop using the GitHub issue tracker for conversation. If you want to discuss HS, the Discord server invite is linked in the pinned issue.
