### ISSUE TITLE
Game crashes before giving out "OK" response after finishing a level

### ISSUE THREAD

**Issue by melodicafluff79** [RHeavenStudio/HeavenStudio#678]
### Describe the bug

The game is really well made, i have to admit, but i was surprised to see it crashing before it could give me the rating after finishing a level. It doesn't matter which level i was playing. As long as i had the "OK" rating, it would just crash.

### How to reproduce the bug?

I don't really know, i suppose i've already explained it on the description. 
I am playing on a machine that has a second gen i5, generic Intel HD graphics chip, with 4 gigs of ram.

![image](https://github.com/RHeavenStudio/HeavenStudio/assets/94212336/48ecaa50-92fd-4ab7-8831-b449416a6991)

**Comment by melodicafluff79** [comment]
![image](https://github.com/RHeavenStudio/HeavenStudio/assets/94212336/82e6f8d1-adb0-49b5-91e2-a1c19d0a83e8)

**Comment by ThatZeoMan** [comment]
Can you send your log file?

**Comment by minenice55** [comment]
closing for now, need log file
