### ISSUE TITLE
GPL License incompatibility

### ISSUE THREAD

**Issue by mdsitton** [RHeavenStudio/HeavenStudio#698]
Unity is not legally compatible with GPL licensed code. Meaning that binaries under the terms of the license cannot be legally distributed because you cannot under the GPL get the full source code of the whole program as unity is closed source.

https://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic

Discussion about this issue on unity forums for reference:
https://forum.unity.com/threads/gnu-gpl-3-open-source-license-and-unity-question.590035/

Might be best to re-license the project under LGPL or maybe MPL?

**Comment by CarbyDood** [comment]
Yeah i agree, licenses are actually way more important than you think! keeps ya outta trouble

**Comment by minenice55** [comment]
good timing because I was already considering re-licensing our stuff, just unsure how to go about things since this was the license used by the project we forked from. LGPL probably makes the most sense for us
