### ISSUE TITLE
[suggestion] Hold pad while releasing A to flick.

### ISSUE THREAD

**Issue by nycki93** [RHeavenStudio/HeavenStudio#731]
### Is your feature request related to a problem? Please describe.

As far as I can tell, the current way to "flick" in games like Rockers etc is to release one button and quickly press another one. This works, but it just doesn't feel very "rhythm heaven-y" to me to have to press a button on both the start and end of the flick. 

### Describe your suggestion

Fundamentally, a flick is a "secondary release", the same way the B button or the d-pad is a "secondary press". So I think the most intuitive solution to button-flicking is to combine the two! I've rigged this up with some Steam Input shenanigans and it feels very natural to me. Pressing and releasing the A button does a "normal release", but holding both A and d-pad and then releasing A is a "flick release".

### Describe alternatives you've considered

The ideal solution is of course to use a touchpad or joystick input, where "hold stick to outer ring" is a tap, a slow return to center is a normal release, and a fast return to center is a flick release. Then you could literally "flick" something just like on the DS. But I think that some sort of a hold-while-releasing modifier would be easier to learn, and it fits the existing language of using the d-pad as a secondary tap input in games such as Catchy Tune.

### Additional context

To test this with steam input:
- start with controller layout "Keyboard Gamepad".
- create a new action layer "flick".
- on the "flick" action layer, add an extra command to the A button.
  - command 2 type: release press. command: I key. settings: fire end delay 25.
  - command 2 sub-command: J key.
- on the main action layer, add an extra command to d-pad up.
  - command 2: hold action layer "flick".
- repeat this extra command for all d-pad inputs.

**Comment by nycki93** [comment]
Alternately, we could patch Rockers specifically to have a press and release _always_ be a flick, and use the B button to mute without charging another flick, mirroring the logic used in Marching Orders.

**Comment by blank3times** [comment]
D-Pad would probably make some people revolt, but it could be nice to have the B be mute in addition to the current controls.

**Comment by AstrlJelly** [comment]
this doesn't really work
i can tell you this because i made octopus machine :) i tried very hard to get it to work well on pad, where releasing normally was a normal release, but holding dpad and releasing was a pop. it wasn't intuitive nor was it fun to play

**Comment by nycki93** [comment]
Hmm. That's fair. In that case I'd suggest handling this on a case by case basis, I've put some thoughts on that here #736
