### ISSUE TITLE
[suggestion] Remove pseudo-flick from rockers, octopus machine, splashdown, etc

### ISSUE THREAD

**Issue by nycki93** [RHeavenStudio/HeavenStudio#736]
### Is your feature request related to a problem? Please describe.

Tapping two buttons to flick is a clever workaround but it _feels wrong_ on every game that uses it at least that I've tried; I've only played through Lush Remix and haven't joined the Discord. (Side note: it would be great if we had an official forum somewhere on the _public_ web to link to level downloads).

### Describe your suggestion

The good news is that this is fixable, the bad news is that it kinda has to be done case by case. 

Megamix adjusts Rhythm Rally and Built To Scale (DS) by just replacing the flick with a tap. It's the only action you can perform, so this is fine. In Glee Club and Karate Man Kicks, the "flick" and "release" cues are combined, and the game just decides contextually which one you meant to do. Splashdown could be adapted the same way, just combine the two release cues into one.

Rockers _could_ be adapted in this way, but I think it would be a lot more fun to approach it using B as a 'stop' action, like in Marching Orders and Sumo Brothers. Basically, press and release A to strum, press B to mute.

Octopus Machine doesn't really work with either of these approaches. The two release actions are intentionally different and shouldn't be lumped together. My instinct is that for this one we should get rid of the held button entirely. Tap once to breathe in, tap again to breathe out, or tap B instead to pop. We could technically do this for splashdown, but splashdown's slower patterns make it a good candidate for transitions into and out of hold notes... I'm really just arbitrarily deciding that I don't think octopus machine makes a good hold note transition. I'm happy to hear arguments on this.

**Comment by blank3times** [comment]
It's about the same level of detail as simple tap in Megamix when there's no flicking. Unfortunate, but it is what it is and it's probably the smoothest gameplay-wise.
