### ISSUE TITLE
Dropdown doesn't work

### ISSUE THREAD

**Issue by PristineC** [RHeavenStudio/HeavenStudio#775]
### Describe the bug

When you right-click on a customizable game event that has a dropdown, it bugs out.

### How to reproduce the bug?

- Open Heaven Studio
- Press "Create"
- Add a customizable game event that has a dropdown
- Click on it

### Screenshots/Videos

<img width="710" alt="Screenshot 2024-03-10 at 12 16 18 AM" src="https://github.com/RHeavenStudio/HeavenStudio/assets/129701959/29926a13-cfdb-4a22-a115-de9e443cde1f">

### What Operating System(s) were you using?

MacOS

**Comment by AstrlJelly** [comment]
yep, this is known. it'll be fixed pretty soon

**Comment by PristineC** [comment]
Okay, thanks!
