### ISSUE TITLE
(Nightly) Fillbots breaks when stacking two bots ontop of eachother

### ISSUE THREAD

**Issue by ookiooclapclap** [RHeavenStudio/HeavenStudio#866]
### Describe the bug

Basically, if you make it so that you have to fill two bots at the same time in Fillbots, it completely breaks - even after deleting both of the commands

### How to reproduce the bug?

Stack two "medium bot" commands in Fillbots.

### What Operating System(s) were you using?

Windows 10/11

**Comment by wookywok** [comment]
Is Fillbots the first game in the remix? A lot of nightly-exclusive games break when they're first in the remix right now, it has something to do with how games are loaded iirc

**Comment by ookiooclapclap** [comment]
The problem did appear when Fillbots was the first game in the remix.

**Comment by SuperMiguek** [comment]
Yep as said multiple time
Most lf exclusive nightly games break when they are first on the remix

**Comment by ookiooclapclap** [comment]
Closed as not planned - because, well, why would you need to stack 2 bots in Fillbots?
