### ISSUE TITLE
Crashing when conecting my xbox controller

### ISSUE THREAD

**Issue by Kik07L** [RHeavenStudio/HeavenStudio#883]
### Describe the bug

so when i lunch the game without my xbox controller conected to my pc everything work properly but when i conect my xbox controller and search for new controller the game freezes and close by itself, so i tried tu lunch the game with my controller connected and it stops working after the unity logo

### How to reproduce the bug?

conect a xbox controller with a usb c cable and lunch the game...

### What Operating System(s) were you using?

windows

### Log file

```shell
Mono path[0] = 'C:/Users/Kik07L/Downloads/HeavenStudio_Win64_101/Heaven Studio_Data/Managed'
Mono config path = 'C:/Users/Kik07L/Downloads/HeavenStudio_Win64_101/MonoBleedingEdge/etc'
Initialize engine version: 2021.3.21f1 (1b156197d683)
[Subsystems] Discovering subsystems at path C:/Users/Kik07L/Downloads/HeavenStudio_Win64_101/Heaven Studio_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 2060 (ID=0x1f08)
    Vendor:   NVIDIA
    VRAM:     5954 MB
    Driver:   31.0.15.5176
Begin MonoManager ReloadAssembly
- Completed reload, in  0.124 seconds
<RI> Initializing input.
<RI> Input initialized.
<RI> Initialized touch support.
UnloadTime: 0.744400 ms
```

**Comment by saladplainzone** [comment]
Hello! We currently don't support Xbox controllers, but this is still odd behavior, we may look into it.

**Comment by Kik07L** [comment]
> Hello! We currently don't support Xbox controllers, but this is still odd behavior, we may look into it.

oh okey ! thx :D
