### ISSUE TITLE
Perfect breaks when Space Soccer is offbeat

### ISSUE THREAD

**Issue by FoaxZed** [RHeavenStudio/HeavenStudio#887]
### Describe the bug

When Space Soccer is placed on the off-beat, the perfect will be disabled, even when autoplay is on. Moving it back to the onbeat fixes this

### How to reproduce the bug?

Place Space Soccer's "ball dispense" on the offbeat

### Screenshots/Videos

https://github.com/RHeavenStudio/HeavenStudio/assets/91384069/1c721e57-b774-47df-b2de-70c1b787d4a2

### What Operating System(s) were you using?

Windows 10/11

### Additional context

Not sure if this is because I'm playing on Nightly mode

**Comment by AstrlJelly** [comment]
this is known, but you shouldn't really ever have it on the offbeat anyways
