### ISSUE TITLE
(Nightly) Frog Hop not in correct position when sorting chronologically

### ISSUE THREAD

**Issue by ookiooclapclap** [RHeavenStudio/HeavenStudio#918]
### Describe the bug

I mean, the title basically sums it up... Frog Hop is not in the correct position when sorting chronologically in the game selection menu.

### How to reproduce the bug?

Press "Sort chronologically" in the editor.

### What Operating System(s) were you using?

Windows 10/11

**Comment by blank3times** [comment]
If it's all the way at the bottom that means that asset stuff hasn't been finished yet, since they go together and if one isn't ready then you can't have the other. Don't worry, all the sorting will be right by release!
