### ISSUE TITLE
Controls reset to Mouse every time you restart the pre-compiled Nightly Build

### ISSUE THREAD

**Issue by derpguy125** [RHeavenStudio/HeavenStudio#947]
### Describe the bug

I think it's a bit self-explanatory. Every time I close and re-open the Nightly build, despite what I do, the controller I use is immediately reset to Mouse, despite the fact that it was on Keyboard before.

### How to reproduce the bug?

1. Download the Nightly build from the README file
2. Open it
3. Set control style to Keyboard
4. Save, close
5. reopen game
6. see that the controls have been reset to mouse.

### Screenshots/Videos

https://file.garden/XYkr7LcqBDVk_X3J/aeiou/2024-05-17%2014-54-13.mp4 (i cant upload the recording directly to github)

### What Operating System(s) were you using?

Windows 10/11

### Log file

```shell
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.088800 ms
No JoyShocks found.
InputJoyshockInitializer.Initialize had no controllers to initialize.
No Joy-Con connected.
InputJoyconPairInitializer.Initialize had no controllers to initialize.
Started Heaven Studio 2d77fb3f 14/05/2024 03:32:16 on WindowsPlayer
We hope you enjoy as much as we did making it!
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
Unloading 391 unused Assets to reduce memory usage. Loaded Objects now: 2587.
Total: 2.506100 ms (FindLiveObjects: 0.171900 ms CreateObjectMapping: 0.067800 ms MarkObjects: 2.068100 ms  DeleteObjects: 0.198000 ms)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 6.277500 ms
Unloading 6 unused Assets to reduce memory usage. Loaded Objects now: 4218.
Total: 2.602500 ms (FindLiveObjects: 0.242400 ms CreateObjectMapping: 0.087000 ms MarkObjects: 2.219300 ms  DeleteObjects: 0.053500 ms)

Assigning controller: Mouse
Disconnecting JoyShocks...
Clearing RIQ Cache...
Setting up 2 worker threads for Enlighten.
```

### Additional context

I don't know how anyone else hasn't had this problem, or why it's just me, but I feel like it's a bit important.

**Comment by ThatZeoGal** [comment]
Not a bug; it will use the device you used to get past the “press any key” prompt.
In r1, a mouse input would be automatically set to keyboard instead. This was changed for the nightly, but it’ll likely be changed back.

**Comment by derpguy125** [comment]
Thank you for the clarification! I do feel like it should be keyboard by default (or controller if you have one plugged in,) with mouse being an optional sort of "You can do this too" thing, but that doesn't really matter right now, as my complaint has been explained to be "not a bug."
