### ISSUE TITLE
removal from Itch.io

### ISSUE THREAD

**Issue by Username-kyle-325** [RHeavenStudio/HeavenStudio#955]
copyright notice. Please put it back up, but put it under a different name, with the itch.io screenshots not including any RH-related content (v1.02)

**Comment by wookywok** [comment]
if you read the dmca claim, it's a blatantly obvious fake from a copyright abuser. i don't think we need to *actually* worry about dodging around copyright, and we're working to try to get the page back up.

**Comment by saladplainzone** [comment]
Yes, we've sent in a dispute, we're just waiting for Itch to respond back. If it is decided that it will stay down, we will respect that decision, but it will always be available _here_.

**Comment by blank3times** [comment]
![image](https://github.com/RHeavenStudio/HeavenStudio/assets/105398129/3ebb4fc7-1d8c-4e3d-b9c3-5486d6633a2e)

**Comment by AftDawn** [comment]
the takedown notice looks alot more official then before. Is this one legit, or did the troll up his game?
![image](https://github.com/RHeavenStudio/HeavenStudio/assets/42480566/35729264-a597-464a-a65b-516f392510ce)

**Comment by MiiKEmblem** [comment]
This is the exact same takedown notice as it's always been. Still pretty obviously fake if you read it for more than 10 seconds.

Best regards,
<- <ins>Return to itch.io</ins>

**Comment by blank3times** [comment]
The one I posted was a parody, there have been quite a few other parodies as well.

**Comment by AftDawn** [comment]
I don't know what to look for when it comes to false DMCA claims, does Big N handle things a different way/in a different format?

**Comment by wookywok** [comment]
> I don't know what to look for when it comes to false DMCA claims, does Big N handle things a different way/in a different format?

Well, for one, they have the money to hire lawyers who can spell.

**Comment by saladplainzone** [comment]
This is the dispute I put forward to itch on May 18th, have not heard back at all
![image](https://github.com/RHeavenStudio/HeavenStudio/assets/31338325/1f352fa5-dfb7-40b8-bbf5-a0fa10724c76)
